source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'STDebugConsole_Example', :exclusive => true do
  pod "STDebugConsole", :path => "../"
end

target 'STDebugConsole_Tests', :exclusive => true do
  pod "STDebugConsole", :path => "../"

  
end
